resource "kubernetes_role_binding" "root_admin_binding" {
  count = "${length(var.namespaces)}"

  metadata {
    name      = "root-admin-binding"
    namespace = "${var.namespaces[count.index]}"
  }

  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "ClusterRole"
    name      = "cluster-admin"
  }

  subject {
    kind      = "ServiceAccount"
    name      = "common-admin"
    namespace = "kube-system"
  }
}


resource "kubernetes_cluster_role" "fuchicorp_cluster_role" {
  metadata {
    name = "fuchicorp-cluster-role"
  }

  rule {
    api_groups = ["*"]
    verbs      = ["*"]
    resources  = [
                  "bindings",
                  "componentstatuses",
                  "configmaps",
                  "endpoints",
                  "events",
                  "limitranges",
                  "namespaces",
                  "namespaces/finalize",
                  "namespaces/status",
                  "nodes",
                  "nodes/proxy",
                  "nodes/status",
                  "persistentvolumeclaims",
                  "persistentvolumeclaims/status",
                  "persistentvolumes",
                  "persistentvolumes/status",
                  "pods",
                  "pods/attach",
                  "pods/binding",
                  "pods/eviction",
                  "pods/exec",
                  "pods/log",
                  "pods/portforward",
                  "pods/proxy",
                  "pods/status",
                  "podtemplates",
                  "replicationcontrollers",
                  "replicationcontrollers/scale",
                  "replicationcontrollers/status",
                  "resourcequotas",
                  "resourcequotas/status",
                  "serviceaccounts",
                  "services",
                  "services/proxy",
                  "services/status",
                  "apiservices",
                  "apiservices/status",
                  "daemonsets",
                  "daemonsets/status",
                  "deployments",
                  "deployments/rollback",
                  "deployments/scale",
                  "deployments/status",
                  "ingresses",
                  "ingresses/status",
                  "networkpolicies",
                  "podsecuritypolicies",
                  "replicasets",
                  "replicasets/scale",
                  "replicasets/status",
                  "replicationcontrollers",
                  "replicationcontrollers/scale",
                  "controllerrevisions",
                  "daemonsets",
                  "daemonsets/status",
                  "deployments",
                  "deployments/scale",
                  "deployments/status",
                  "replicasets",
                  "replicasets/scale",
                  "replicasets/status",
                  "statefulsets",
                  "statefulsets/scale",
                  "statefulsets/status",
                  "events",
                  "tokenreviews",
                  "localsubjectaccessreviews",
                  "selfsubjectaccessreviews",
                  "selfsubjectrulesreviews",
                  "subjectaccessreviews",
                  "horizontalpodautoscalers",
                  "horizontalpodautoscalers/status",
                  "jobs",
                  "jobs/status",
                  "certificatesigningrequests",
                  "certificatesigningrequests/approval",
                  "certificatesigningrequests/status",
                  "networkpolicies",
                  "poddisruptionbudgets",
                  "poddisruptionbudgets/status",
                  "clusterrolebindings",
                  "clusterroles",
                  "rolebindings",
                  "roles",
                  "storageclasses",
                  "mutatingwebhookconfigurations",
                  "validatingwebhookconfigurations",
                  "customresourcedefinitions",
                  "customresourcedefinitions/status",
                  "connectors",
                  "refreshtokens",
                  "authrequests",
                  "signingkeies",
                  "authcodes",
                  "oauth2clients",
                  "offlinesessionses",
                  "passwords",
                  "meshpolicies",
                  "policies",
                  "rbacconfigs",
                  "servicerolebindings",
                  "serviceroles",
                  "servicecontrolreports",
                  "signalfxs",
                  "apikeys",
                  "authorizations",
                  "httpapispecbindings",
                  "reportnothings",
                  "fluentds",
                  "kubernetesenvs",
                  "quotaspecbindings",
                  "servicecontrols",
                  "circonuses",
                  "adapters",
                  "listcheckers",
                  "listentries",
                  "deniers",
                  "instances",
                  "attributemanifests",
                  "rbacs",
                  "rules",
                  "stdios",
                  "edges",
                  "redisquotas",
                  "metrics",
                  "handlers",
                  "logentries",
                  "opas",
                  "memquotas",
                  "templates",
                  "solarwindses",
                  "bypasses",
                  "tracespans",
                  "checknothings",
                  "noops",
                  "httpapispecs",
                  "stackdrivers",
                  "statsds",
                  "quotas",
                  "kuberneteses",
                  "quotaspecs",
                  "prometheuses",
                  "destinationrules",
                  "virtualservices",
                  "gateways",
                  "serviceentries",
                  "envoyfilters", ]
  }
}